title: Artur Cremonez
description: "Ciência da Computação. Notas de estudo por Artur Cremonez."
theme: minima
google_analytics: G-V21L7J459R
url: "https://arturcremonez.github.io"
baseurl: ""
plugins:
  - jekyll-sitemap
